spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://equipment.cqidwg1vvp0o.ap-northeast-2.rds.amazonaws.com:3306/equipment?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: equipment
    password: Equipment12!!
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis

  redis:
    host: redis
    port: 6379

jwt:
  refresh-exp: 2592000000
  access-exp: 3600000
  prefix: Bearer
  header: Authorization
  secret-key: difoi3iu2jioj132890u8979f7dxj1k2nbjkmhcxuasijf879687912yhjkhsdfuoiljkh13

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  access-key: AKIAQ2JYNXZ5LVXY4A23
  secret-key: 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
  region: ap-northeast-2
  bucket: dgswequipment
  url: https://dgswequipment.s3.ap-northeast-2.amazonaws.com/

app:
  dauth:
    ras-url: http://10.255.255.148:8080
    auth-url: http://dauth.b1nd.com/api
    open-url: http://open.dodam.b1nd.com/api
    client-id: af3a177fb1d3425b8828c072feebe63d2122c01c191b42d9aab6748864c7de97
    client-secret: 80134adc086046679920af1203433d702aa7174a94ac43aaa43f2a7c27486bbc

server:
  port: 2542
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false